# ----
# Site

title: DaSCH Service Platform
url: https://dsp.dasch.swiss
baseurl:
google_analytics_key:

company:
  company_name: Data and Service Center for the Humanities (DaSCH)
  mission_statement: Data and Service Center for the Humanities (DaSCH).
  address: Gewerbestrasse 24, 4123 Allschwil
  phone: +41 61 207 04 89
  www: dasch.swiss
  email: info@dasch.swiss
  twitter: DaSCHSwiss
  github: dasch-swiss




links:
  knora: <a href="https://dsp.dasch.swiss">DaSCH Service Platform</a>
  knora-docs: <a href="https://docs-api.dasch.swiss">Documentation</a>
  sipi: <a href="https://sipi.io">Sipi</a>
  knora-app: <a href="https://dasch-swiss.github.io/knora-app">Knora-App</a>
  dhlab: <a href="http://dhlab.unibas.ch">Digital Humanities Lab</a>
  dasch: <a href="http://dasch.swiss">Data and Service Center for the Humanities</a>
  unibas: <a href="http://unibas.ch">University of Basel</a>


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/touch-icon.png
description: The DaSCH Service Platform is a software framework for storing, sharing, and working with primary sources and data in the humanities.
author:
  name: Data and Service Center for the Humanities, University of Basel
  email: info@dasch.swiss
  twitter: DaSCHSwiss # twitter username without the @ symbol
social:
  name: Data and Service Center for the Humanities, University of Basel
  links:
    - https://dasch.swiss
    - https://github.com/dasch-swiss
    

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
